source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'Backgroundable_Tests', :exclusive => true do
  pod "Backgroundable", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
